# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2986c488789ec5cdf98b63e13431da9"
name = "rb-mus"
handle = "rb-mus"
application_url = "https://obj-currently-arch-adjustment.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c0eb237e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://obj-currently-arch-adjustment.trycloudflare.com/auth/callback",
  "https://obj-currently-arch-adjustment.trycloudflare.com/auth/shopify/callback",
  "https://obj-currently-arch-adjustment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
