# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "813209388aa95e2a9e748086d6dbbf7e"
name = "rb-mus"
handle = "rb-mus-1"
application_url = "https://depot-comfort-viewer-rebates.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tayyab-products.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://depot-comfort-viewer-rebates.trycloudflare.com/auth/callback",
  "https://depot-comfort-viewer-rebates.trycloudflare.com/auth/shopify/callback",
  "https://depot-comfort-viewer-rebates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
