# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f02f6f57caec3d69e6f5b7725e6df9a"
name = "rb-mus"
handle = "rb-mus"
application_url = "https://extras-airport-builders-poly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tayyab-products.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes

scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://extras-airport-builders-poly.trycloudflare.com/auth/callback",
  "https://extras-airport-builders-poly.trycloudflare.com/auth/shopify/callback",
  "https://extras-airport-builders-poly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
